name: Release

on:
  push:
    branches:
      - main

jobs:
  new-release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        packages:
          - package1
          - package2

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        # Note: Version 20.0.0 of semantic-release and later is currently incompatible with cycjimmy/semantic-release-action, since it requires Node.js 18. GitHub does not provide this environment yet for JavaScript actions. 
        semantic_version: 19
        branch: main
        extends: |
          semantic-release-monorepo@7.0.5
        working_directory: ${{ matrix.packages }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
